config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  root 'articles#index'

  get '/news', to: 'articles#index'
  get '/news/:id', to: 'articles#show'
  get '/newcomments', to: 'comments#index'

  get '/submit', to: 'articles#new'
  post '/submit', to: 'articles#create'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'about#index'

  get '/v0/item/:id', to: 'items#show'
  post '/v0/item/create', to: 'items#create'

  resources :articles do
    resources :comments, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  # specify that if the articles item that the comments belong to is destroyed, so
  # are they
  has_many :comments, dependent: :destroy

  # validate that the fields must be present
  # TODO: add validation
  validates_format_of :url,
    allow_blank: true,
      :with => URI::regexp(%w(http https)),
        message: "must be a valid url"


  validates :title,
    length: {
      in: 10..199,
        message: "must be between 10 and 200 characters"
    },
    presence: true

  def to_s
    "{ \"title\": \"#{self[:title]}\",\
\"url\": \"#{self[:url]}\",\
\"by\":\"#{self[:by]}\",\
\"created_at\":\"#{self[:created_at].to_i}\" }"
  end
end

app/models/articles.rb
class Article < ApplicationRecord
  # specify that if the articles item that the comments belong to is destroyed, so
  # are they
  has_many :comments, dependent: :destroy

  # validate that the fields must match regex
  validates :text, :url, :title, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # don't require login to view articles, only to create, edit, and destroy
  skip_before_action :require_login, only: [:show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order('articles.created_at DESC').reverse
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    if Article.exists?(params[:id])
      @article = Article.find(params[:id])
      @comments = Comment.all.where(article_id: @article.id).order('comments.created_at DESC')
    else
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Article with id #{params[:id]} not found" }
      end
    end
  end

  # GET /articles/new
  def new
    @articles = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @articles = Article.new(articles_params)

    respond_to do |format|
      if @articles.save
        format.html { redirect_to @articles, notice: 'article posted, more at 5.' }
        format.json { render :show, status: :created, location: @articles }
      else
        format.html { render :new }
        format.json { render json: @articles.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(articles_params)
        format.html { redirect_to @article, notice: 'This just in, article has been changed!' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    Article.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Removed your article!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articles
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articles_params
      params.require(:article).permit(:by, :url, :title)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper

end

app/views/articles/_comment.html.erb
<%= @comments.each do |comment| %>
  <div class="article-comment">
    <p>
      <%= comment[:body] %>
    </p>
    <p>
      Posted by <%= get_username(comment[:user_id]) %> <%= time_ago_in_words(comment[:created_at]) %> ago
    </p>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Set this field to hidden and use the current users username to save -->
  <!-- Create a new hidden field to pass the username to the db -->
  <div class="field">
    <%= form.hidden_field :by, :value => get_username(session[:user_id]) %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :article_title, class:"form-control article-title-text", rows:3 %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :article_url, class:"form-control" %>
  </div>

  <div class="actions" align="left">
    <%= form.submit class:"btn btn-primary col-md-3" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing articles</h1>

<%= render 'form', article: @articles %>

<%= link_to 'Show', @articles %> |
<%= link_to 'Back', articles_index_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="articles col-md-10">
    <% @articles.each do |article| %>
      <div class="article ">
        <p><%= article.id %>.  <%= link_to article.title, article %>  (<%= link_to article.url, article.url %>)</p>
        <p class="text-muted" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Posted by <%= article.by %> <%= time_ago_in_words(article.created_at) %> ago.</p>
      </div>
    <% end %>
    <%= link_to 'Post New Article', new_article_path %>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

          <h1>Post a new article</h1>

          <%= render 'form', article: @articles %>

          <%= link_to 'Back', articles_path %>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6"></div>
      </div>
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2"></div>
    </div>
  </div>

app/views/articles/show.html.erb
<% content_for :title, @article.title %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="articles col-md-10">
      <!-- <p id="notice"><%= notice %></p> -->
      <p>
        <strong>
          <%= @article.title %>
          (<%= @article.url %>)
        </strong>
      </p>

      <p class="text-muted">&nbsp;&nbsp;&nbsp;by
        <%= @article.by %>
        <%= time_ago_in_words(@article.created_at) %>
        ago.
      </p>

      <%= form_for [@article, Comment.new] do |f| %>
      <%= f.label :body, "Add a new comment!" %><br/>
      <%= f.text_area :body, class:"form-control col-md-6", rows:4%>
      <%= f.hidden_field :user_id, :value => session[:user_id]%>

      <%= f.submit "Submit comment", class: "btn btn-primary col-md-2" %>
      <% end %>
      <div>

        <% @comments.each do |comment| %>
        <div class="comment">
          <p class="comment-detail text-muted">
            <%= get_username(comment.user_id) %>&nbsp |&nbsp
            <%= time_ago_in_words(comment.created_at) %>
            ago
          </p>
          <p class="comment-body"><%= comment.body %></p>
        </div>
        <% end %>

      </div>
      <%= link_to 'Edit', edit_article_path(@article) %>
      |
      <%= link_to 'Back', news_path %>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>